icacls ".\admin-dev\autoupgrade" /grant Everyone:F /t /c /q
icacls ".\app\config" /grant Everyone:F /t /c /q
icacls ".\cache" /grant Everyone:F /t /c /q
icacls ".\config" /grant Everyone:F /t /c /q
icacls ".\download" /grant Everyone:F /t /c /q
icacls ".\img" /grant Everyone:F /t /c /q
icacls ".\log" /grant Everyone:F /t /c /q
icacls ".\mails" /grant Everyone:F /t /c /q
icacls ".\modules" /grant Everyone:F /t /c /q
icacls ".\override" /grant Everyone:F /t /c /q
icacls ".\themes" /grant Everyone:F /t /c /q
icacls ".\translations" /grant Everyone:F /t /c /q
icacls ".\upload" /grant Everyone:F /t /c /q
icacls ".\var" /grant Everyone:F /t /c /q